//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pekspro.RadioStorm.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pekspro.RadioStorm.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …Sveriges Radio som gör sådana här projekt möjliga..
        /// </summary>
        public static string About_Credits_Line1 {
            get {
                return ResourceManager.GetString("About_Credits_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …Joakim Karlsson för ikonen och grafisk rådgivning..
        /// </summary>
        public static string About_Credits_Line2 {
            get {
                return ResourceManager.GetString("About_Credits_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …alla er som önskat förbättringar och hittat brister i programmet..
        /// </summary>
        public static string About_Credits_Line3 {
            get {
                return ResourceManager.GetString("About_Credits_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …dig som just nu använder RadioStorm! :-).
        /// </summary>
        public static string About_Credits_Line4 {
            get {
                return ResourceManager.GetString("About_Credits_Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tack till….
        /// </summary>
        public static string About_Credits_Title {
            get {
                return ResourceManager.GetString("About_Credits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioStorm är utvecklat av PEK&apos;s Productions oberoende av Sveriges Radio. Programmet använder sig av Sveriges Radios öppna API..
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknar du något i RadioStorm? Kontakta oss!.
        /// </summary>
        public static string About_Email_Note {
            get {
                return ResourceManager.GetString("About_Email_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        public static string About_Header_Email {
            get {
                return ResourceManager.GetString("About_Header_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemsida.
        /// </summary>
        public static string About_Header_Webbpage {
            get {
                return ResourceManager.GetString("About_Header_Webbpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablå.
        /// </summary>
        public static string Channel_ScheduleEpisodes {
            get {
                return ResourceManager.GetString("Channel_ScheduleEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mer om {0}.
        /// </summary>
        public static string ChannelInfo_MoreAbout {
            get {
                return ResourceManager.GetString("ChannelInfo_MoreAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den här kanalen har ingen tablå..
        /// </summary>
        public static string ChannelInfo_NoEpisodes {
            get {
                return ResourceManager.GetString("ChannelInfo_NoEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du lägga till {0} kanaler som favoriter?.
        /// </summary>
        public static string Channels_AddMultipleFavoritesWarning {
            get {
                return ResourceManager.GetString("Channels_AddMultipleFavoritesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägga till favoriter.
        /// </summary>
        public static string Channels_AddMultipleFavoritesWarning_Title {
            get {
                return ResourceManager.GetString("Channels_AddMultipleFavoritesWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök kanaler.
        /// </summary>
        public static string Channels_SearchChannels {
            get {
                return ResourceManager.GetString("Channels_SearchChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanaler.
        /// </summary>
        public static string Channels_Title {
            get {
                return ResourceManager.GetString("Channels_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just nu spelas ingenting. Gå till en kanal eller program och hitta något trevligt att lyssna på ;-).
        /// </summary>
        public static string CurrentPlaying_Nothing_Description {
            get {
                return ResourceManager.GetString("CurrentPlaying_Nothing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoppsan.
        /// </summary>
        public static string CurrentPlaying_NothingTitle {
            get {
                return ResourceManager.GetString("CurrentPlaying_NothingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelas nu.
        /// </summary>
        public static string CurrentPlaying_Title {
            get {
                return ResourceManager.GetString("CurrentPlaying_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga data hittades..
        /// </summary>
        public static string DowloadControl_NoDataFound {
            get {
                return ResourceManager.GetString("DowloadControl_NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Försök igen.
        /// </summary>
        public static string DownloadControl_Retry {
            get {
                return ResourceManager.GetString("DownloadControl_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoppsan! Något gick fel :-(.
        /// </summary>
        public static string DownloadControl_SomethingWentWrong {
            get {
                return ResourceManager.GetString("DownloadControl_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to När du har laddat ned avsnitt ser du dom här..
        /// </summary>
        public static string Downloads_Empty {
            get {
                return ResourceManager.GetString("Downloads_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedladdningar.
        /// </summary>
        public static string Downloads_Title {
            get {
                return ResourceManager.GetString("Downloads_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har väldigt mycket nedladdningar. Se över dessa om du vill att fler nedladdningar ska göras automatiskt..
        /// </summary>
        public static string Downloads_Toast_ToManyDownloads_Toast_Message {
            get {
                return ResourceManager.GetString("Downloads_Toast_ToManyDownloads_Toast_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oj oj oj!.
        /// </summary>
        public static string Downloads_Toast_ToManyDownloads_Toast_Title {
            get {
                return ResourceManager.GetString("Downloads_Toast_ToManyDownloads_Toast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns för många nedladdningar.
        /// </summary>
        public static string Downloads_ToManyDownloads_ButtonText {
            get {
                return ResourceManager.GetString("Downloads_ToManyDownloads_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har just nu {0} nedladdningar. Om du har fler än {1} nedladdningar kommer det inte laddas ned några fler avsnitt automatiskt. Du kan fortfarande ladda ned avsnitt manuellt..
        /// </summary>
        public static string Downloads_ToManyDownloads_Description {
            get {
                return ResourceManager.GetString("Downloads_ToManyDownloads_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämtad ({0:F1} MB).
        /// </summary>
        public static string DownloadStatus_Completed {
            get {
                return ResourceManager.GetString("DownloadStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämtar....
        /// </summary>
        public static string DownloadStatus_Downloading {
            get {
                return ResourceManager.GetString("DownloadStatus_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämtar ({0}% av {1:F1} MB).
        /// </summary>
        public static string DownloadStatus_Downloading_InProgress {
            get {
                return ResourceManager.GetString("DownloadStatus_Downloading_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL.
        /// </summary>
        public static string DownloadStatus_Error {
            get {
                return ResourceManager.GetString("DownloadStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Väntar....
        /// </summary>
        public static string DownloadStatus_Waiting {
            get {
                return ResourceManager.GetString("DownloadStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det här avsnittet har ingen låtlista..
        /// </summary>
        public static string EpisodeInfo_NoSongs {
            get {
                return ResourceManager.GetString("EpisodeInfo_NoSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa fler avsnitt från {0}.
        /// </summary>
        public static string EpisodeInfo_ShowMoreEpisodes {
            get {
                return ResourceManager.GetString("EpisodeInfo_ShowMoreEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa spellista.
        /// </summary>
        public static string Episodes_AutoCreatePlayList {
            get {
                return ResourceManager.GetString("Episodes_AutoCreatePlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort nedladdningar.
        /// </summary>
        public static string Episodes_DeleteDownloads {
            get {
                return ResourceManager.GetString("Episodes_DeleteDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladda ned.
        /// </summary>
        public static string Episodes_DownloadSelected {
            get {
                return ResourceManager.GetString("Episodes_DownloadSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avsnitt.
        /// </summary>
        public static string Episodes_Episodes {
            get {
                return ResourceManager.GetString("Episodes_Episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillgänglig {0} dagar till {1}.
        /// </summary>
        public static string Episodes_ExpireNote_MultipleDays {
            get {
                return ResourceManager.GetString("Episodes_ExpireNote_MultipleDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillgänglig {1} fram till {0}.
        /// </summary>
        public static string Episodes_ExpireNote_OneDayOrLess {
            get {
                return ResourceManager.GetString("Episodes_ExpireNote_OneDayOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to med musik.
        /// </summary>
        public static string Episodes_ExpireNote_WithMusic {
            get {
                return ResourceManager.GetString("Episodes_ExpireNote_WithMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämta alla.
        /// </summary>
        public static string Episodes_GetAll {
            get {
                return ResourceManager.GetString("Episodes_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Episodes_Information {
            get {
                return ResourceManager.GetString("Episodes_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nästa: {0}.
        /// </summary>
        public static string Episodes_NextEpisode {
            get {
                return ResourceManager.GetString("Episodes_NextEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det här avsnittet kan inte spelas upp..
        /// </summary>
        public static string Episodes_NoAudioAvailible {
            get {
                return ResourceManager.GetString("Episodes_NoAudioAvailible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det här avsnittet finns inte tillgängligt för nedladdning..
        /// </summary>
        public static string Episodes_NoDownloadAvailible {
            get {
                return ResourceManager.GetString("Episodes_NoDownloadAvailible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga avsnitt hittades..
        /// </summary>
        public static string Episodes_NoEpisodesFound {
            get {
                return ResourceManager.GetString("Episodes_NoEpisodesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Föregående: {0}.
        /// </summary>
        public static string Episodes_PreviousEpisode {
            get {
                return ResourceManager.GetString("Episodes_PreviousEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök avsnitt.
        /// </summary>
        public static string Episodes_SearchEpisodes {
            get {
                return ResourceManager.GetString("Episodes_SearchEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markera som spelad.
        /// </summary>
        public static string Episodes_SetAsListened {
            get {
                return ResourceManager.GetString("Episodes_SetAsListened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markera som ej spelad.
        /// </summary>
        public static string Episodes_SetAsNotListened {
            get {
                return ResourceManager.GetString("Episodes_SetAsNotListened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markera som spelad.
        /// </summary>
        public static string Episodes_SetMultipleAsListened_Title {
            get {
                return ResourceManager.GetString("Episodes_SetMultipleAsListened_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du markera {0} avsnitt som spelade?.
        /// </summary>
        public static string Episodes_SetMultipleAsListenedWarning {
            get {
                return ResourceManager.GetString("Episodes_SetMultipleAsListenedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markera som ej spelad.
        /// </summary>
        public static string Episodes_SetMultipleAsNotListened_Title {
            get {
                return ResourceManager.GetString("Episodes_SetMultipleAsNotListened_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du markera {0} avsnitt som ej spelade?.
        /// </summary>
        public static string Episodes_SetMultipleAsNotListenedWarning {
            get {
                return ResourceManager.GetString("Episodes_SetMultipleAsNotListenedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa ospelat avsnitt.
        /// </summary>
        public static string Episodes_ShowNotPlayedEpisode {
            get {
                return ResourceManager.GetString("Episodes_ShowNotPlayedEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns fler avsnitt..
        /// </summary>
        public static string Episodes_TooManyEpisodes {
            get {
                return ResourceManager.GetString("Episodes_TooManyEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Övrigt.
        /// </summary>
        public static string Episodes_UnknownGroupName {
            get {
                return ResourceManager.GetString("Episodes_UnknownGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga avsnitt hittades..
        /// </summary>
        public static string EpisodeSearch_NoEpisodesFound {
            get {
                return ResourceManager.GetString("EpisodeSearch_NoEpisodesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök avsnitt.
        /// </summary>
        public static string EpisodeSearch_SearchEpisodes {
            get {
                return ResourceManager.GetString("EpisodeSearch_SearchEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök program.
        /// </summary>
        public static string EpisodeSearch_SearchPrograms {
            get {
                return ResourceManager.GetString("EpisodeSearch_SearchPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} avsnitt hittades..
        /// </summary>
        public static string EpisodeSearch_SomeEpisodesFound {
            get {
                return ResourceManager.GetString("EpisodeSearch_SomeEpisodesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till några godbitar.
        /// </summary>
        public static string Favorites_AddRecommendedFavorites {
            get {
                return ResourceManager.GetString("Favorites_AddRecommendedFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort favoriter.
        /// </summary>
        public static string Favorites_ButtonRemoveFavorites {
            get {
                return ResourceManager.GetString("Favorites_ButtonRemoveFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanaler.
        /// </summary>
        public static string Favorites_Group_Channels {
            get {
                return ResourceManager.GetString("Favorites_Group_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Favorites_Group_Programs {
            get {
                return ResourceManager.GetString("Favorites_Group_Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå till Kanaler eller Program och lägg till dina favoriter. Det kommer att löna sig ;-).
        /// </summary>
        public static string Favorites_NothingPlaying {
            get {
                return ResourceManager.GetString("Favorites_NothingPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ta bort {0} favoriter?.
        /// </summary>
        public static string Favorites_RemoveMultipleFavoritesWarning {
            get {
                return ResourceManager.GetString("Favorites_RemoveMultipleFavoritesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort favoriter.
        /// </summary>
        public static string Favorites_RemoveMultipleFavoritesWarning_Title {
            get {
                return ResourceManager.GetString("Favorites_RemoveMultipleFavoritesWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synkronisera.
        /// </summary>
        public static string Favorites_Synchronize_Label {
            get {
                return ResourceManager.GetString("Favorites_Synchronize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synkronisera favoriter och vad du lyssnat på med andra enheter..
        /// </summary>
        public static string Favorites_Synchronize_ToolTip {
            get {
                return ResourceManager.GetString("Favorites_Synchronize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synkroniserar favoriter och vad du lyssnat på med andra enheter....
        /// </summary>
        public static string Favorites_Synchronize_ToolTip_Running {
            get {
                return ResourceManager.GetString("Favorites_Synchronize_ToolTip_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriter.
        /// </summary>
        public static string Favorites_Title {
            get {
                return ResourceManager.GetString("Favorites_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla Sveriges Radios kanaler.
        /// </summary>
        public static string Favorites_Tooltips_Channels {
            get {
                return ResourceManager.GetString("Favorites_Tooltips_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa dina nedladdade avsnitt.
        /// </summary>
        public static string Favorites_Tooltips_Downloads {
            get {
                return ResourceManager.GetString("Favorites_Tooltips_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dina favoriter.
        /// </summary>
        public static string Favorites_Tooltips_Favorites {
            get {
                return ResourceManager.GetString("Favorites_Tooltips_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla Sveriges Radios program.
        /// </summary>
        public static string Favorites_Tooltips_Programs {
            get {
                return ResourceManager.GetString("Favorites_Tooltips_Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historik över vilka avsnitt du nyligen spelat.
        /// </summary>
        public static string Favorites_Tooltips_Recent {
            get {
                return ResourceManager.GetString("Favorites_Tooltips_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inställningar och information om RadioStorm.
        /// </summary>
        public static string Favorites_Tooltips_Settings {
            get {
                return ResourceManager.GetString("Favorites_Tooltips_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej!.
        /// </summary>
        public static string Favorites_Welcome_1 {
            get {
                return ResourceManager.GetString("Favorites_Welcome_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roligt att du har valt att prova RadioStorm. Här visas i normala fall dina favoriter som finns i Sveriges Radio. Just nu vet vi inte vad du gillar så du får se detta istället! :-).
        /// </summary>
        public static string Favorites_Welcome_2 {
            get {
                return ResourceManager.GetString("Favorites_Welcome_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Använd menyn för att se vilka .
        /// </summary>
        public static string Favorites_Welcome_3a {
            get {
                return ResourceManager.GetString("Favorites_Welcome_3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kanaler.
        /// </summary>
        public static string Favorites_Welcome_3b {
            get {
                return ResourceManager.GetString("Favorites_Welcome_3b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  och .
        /// </summary>
        public static string Favorites_Welcome_3c {
            get {
                return ResourceManager.GetString("Favorites_Welcome_3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program.
        /// </summary>
        public static string Favorites_Welcome_3d {
            get {
                return ResourceManager.GetString("Favorites_Welcome_3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  som finns..
        /// </summary>
        public static string Favorites_Welcome_3e {
            get {
                return ResourceManager.GetString("Favorites_Welcome_3e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Klicka på stjärnan på de som du vill ha som favoriter..
        /// </summary>
        public static string Favorites_Welcome_3f {
            get {
                return ResourceManager.GetString("Favorites_Welcome_3f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan synkronisera dina favoriter, vad du har lyssnat på och så vidare mellan dina enheter. Gå in i .
        /// </summary>
        public static string Favorites_Welcome_4a {
            get {
                return ResourceManager.GetString("Favorites_Welcome_4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inställningarna.
        /// </summary>
        public static string Favorites_Welcome_4b {
            get {
                return ResourceManager.GetString("Favorites_Welcome_4b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  för att aktivera detta..
        /// </summary>
        public static string Favorites_Welcome_4c {
            get {
                return ResourceManager.GetString("Favorites_Welcome_4c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha det så kul! :-).
        /// </summary>
        public static string Favorites_Welcome_5 {
            get {
                return ResourceManager.GetString("Favorites_Welcome_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PEK.
        /// </summary>
        public static string Favorites_Welcome_6 {
            get {
                return ResourceManager.GetString("Favorites_Welcome_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psst!.
        /// </summary>
        public static string Favorites_Welcome_7 {
            get {
                return ResourceManager.GetString("Favorites_Welcome_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ha lite tips på några favoriter? Klicka på den här knappen..
        /// </summary>
        public static string Favorites_Welcome_8 {
            get {
                return ResourceManager.GetString("Favorites_Welcome_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till som favorit.
        /// </summary>
        public static string General_AddAsFavorite {
            get {
                return ResourceManager.GetString("General_AddAsFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till som favoriter.
        /// </summary>
        public static string General_AddAsFavorites {
            get {
                return ResourceManager.GetString("General_AddAsFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till i spellista.
        /// </summary>
        public static string General_AddToPlayList {
            get {
                return ResourceManager.GetString("General_AddToPlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladda ned.
        /// </summary>
        public static string General_Download {
            get {
                return ResourceManager.GetString("General_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorit.
        /// </summary>
        public static string General_Favorite {
            get {
                return ResourceManager.GetString("General_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppera efter kategori.
        /// </summary>
        public static string General_GroupByCategory {
            get {
                return ResourceManager.GetString("General_GroupByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppera efter namn.
        /// </summary>
        public static string General_GroupByName {
            get {
                return ResourceManager.GetString("General_GroupByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det här avsnittet är inlagt i spellistan.
        /// </summary>
        public static string General_IsInPlayList {
            get {
                return ResourceManager.GetString("General_IsInPlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sänds nu.
        /// </summary>
        public static string General_Label_CurrentlySending {
            get {
                return ResourceManager.GetString("General_Label_CurrentlySending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senare.
        /// </summary>
        public static string General_Label_Later {
            get {
                return ResourceManager.GetString("General_Label_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längd:.
        /// </summary>
        public static string General_Length {
            get {
                return ResourceManager.GetString("General_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ta bort {0} nedladdningar?.
        /// </summary>
        public static string General_Message_RemoveMultipleDownload_Message {
            get {
                return ResourceManager.GetString("General_Message_RemoveMultipleDownload_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort nedladdningar.
        /// </summary>
        public static string General_Message_RemoveMultipleDownload_Title {
            get {
                return ResourceManager.GetString("General_Message_RemoveMultipleDownload_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nej.
        /// </summary>
        public static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga låtar hittades..
        /// </summary>
        public static string General_NoSongsFound {
            get {
                return ResourceManager.GetString("General_NoSongsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@pekspro.com.
        /// </summary>
        public static string General_Pekspro_EmailAddress {
            get {
                return ResourceManager.GetString("General_Pekspro_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.pekspro.com.
        /// </summary>
        public static string General_Pekspro_Url {
            get {
                return ResourceManager.GetString("General_Pekspro_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fäst till start.
        /// </summary>
        public static string General_Pin {
            get {
                return ResourceManager.GetString("General_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spela.
        /// </summary>
        public static string General_Play {
            get {
                return ResourceManager.GetString("General_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellista.
        /// </summary>
        public static string General_PlayList {
            get {
                return ResourceManager.GetString("General_PlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicerad:.
        /// </summary>
        public static string General_PublishDate {
            get {
                return ResourceManager.GetString("General_PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort.
        /// </summary>
        public static string General_Remove {
            get {
                return ResourceManager.GetString("General_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort som favorit.
        /// </summary>
        public static string General_RemoveAsFavorite {
            get {
                return ResourceManager.GetString("General_RemoveAsFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort nedladdning.
        /// </summary>
        public static string General_RemoveDownload {
            get {
                return ResourceManager.GetString("General_RemoveDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj alla.
        /// </summary>
        public static string General_SelectAll {
            get {
                return ResourceManager.GetString("General_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storlek:.
        /// </summary>
        public static string General_Size {
            get {
                return ResourceManager.GetString("General_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låtlista.
        /// </summary>
        public static string General_SongList {
            get {
                return ResourceManager.GetString("General_SongList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort från start.
        /// </summary>
        public static string General_Unpin {
            get {
                return ResourceManager.GetString("General_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppdatera.
        /// </summary>
        public static string General_Update {
            get {
                return ResourceManager.GetString("General_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om.
        /// </summary>
        public static string GeneralButtonAbout {
            get {
                return ResourceManager.GetString("GeneralButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        public static string GeneralButtonCancel {
            get {
                return ResourceManager.GetString("GeneralButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanaler.
        /// </summary>
        public static string GeneralButtonChannels {
            get {
                return ResourceManager.GetString("GeneralButtonChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedladdningar.
        /// </summary>
        public static string GeneralButtonDownloads {
            get {
                return ResourceManager.GetString("GeneralButtonDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriter.
        /// </summary>
        public static string GeneralButtonFavorites {
            get {
                return ResourceManager.GetString("GeneralButtonFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök.
        /// </summary>
        public static string GeneralButtonFind {
            get {
                return ResourceManager.GetString("GeneralButtonFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är spelad.
        /// </summary>
        public static string GeneralButtonIsListened {
            get {
                return ResourceManager.GetString("GeneralButtonIsListened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string GeneralButtonOk {
            get {
                return ResourceManager.GetString("GeneralButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öppna Facebooksida.
        /// </summary>
        public static string GeneralButtonOpenFacebookPage {
            get {
                return ResourceManager.GetString("GeneralButtonOpenFacebookPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öppna Twittersida.
        /// </summary>
        public static string GeneralButtonOpenTwitterPage {
            get {
                return ResourceManager.GetString("GeneralButtonOpenTwitterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öppna webbsida.
        /// </summary>
        public static string GeneralButtonOpenWebPage {
            get {
                return ResourceManager.GetString("GeneralButtonOpenWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string GeneralButtonProgram {
            get {
                return ResourceManager.GetString("GeneralButtonProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidigare.
        /// </summary>
        public static string GeneralButtonRecent {
            get {
                return ResourceManager.GetString("GeneralButtonRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj alla.
        /// </summary>
        public static string GeneralButtonSelectAll {
            get {
                return ResourceManager.GetString("GeneralButtonSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inställningar.
        /// </summary>
        public static string GeneralButtonSettings {
            get {
                return ResourceManager.GetString("GeneralButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj.
        /// </summary>
        public static string GeneralSelect {
            get {
                return ResourceManager.GetString("GeneralSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} objekt har markerats.
        /// </summary>
        public static string GeneralSelectionMultiple {
            get {
                return ResourceManager.GetString("GeneralSelectionMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inget objekt har markerats.
        /// </summary>
        public static string GeneralSelectionNone {
            get {
                return ResourceManager.GetString("GeneralSelectionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 objekt har markerats.
        /// </summary>
        public static string GeneralSelectionOne {
            get {
                return ResourceManager.GetString("GeneralSelectionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortsätt från där du senast lyssnade.
        /// </summary>
        public static string Player_MenuContinueFromLatestPlayedPosition {
            get {
                return ResourceManager.GetString("Player_MenuContinueFromLatestPlayedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sovtimer.
        /// </summary>
        public static string Player_MenuSleepTimer {
            get {
                return ResourceManager.GetString("Player_MenuSleepTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stäng av sovtimer ({0}:{1}).
        /// </summary>
        public static string Player_MenuSleepTimer_Disable {
            get {
                return ResourceManager.GetString("Player_MenuSleepTimer_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minuter.
        /// </summary>
        public static string Player_MenuSleepTimer_Set {
            get {
                return ResourceManager.GetString("Player_MenuSleepTimer_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastighet.
        /// </summary>
        public static string Player_MenuSpeed {
            get {
                return ResourceManager.GetString("Player_MenuSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snabbt.
        /// </summary>
        public static string Player_MenuSpeed_Fast {
            get {
                return ResourceManager.GetString("Player_MenuSpeed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Player_MenuSpeed_Normal {
            get {
                return ResourceManager.GetString("Player_MenuSpeed_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Långsamt.
        /// </summary>
        public static string Player_MenuSpeed_Slow {
            get {
                return ResourceManager.GetString("Player_MenuSpeed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mycket snabbt.
        /// </summary>
        public static string Player_MenuSpeed_VeryFast {
            get {
                return ResourceManager.GetString("Player_MenuSpeed_VeryFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mycket långsamt.
        /// </summary>
        public static string Player_MenuSpeed_VerySlow {
            get {
                return ResourceManager.GetString("Player_MenuSpeed_VerySlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nästa.
        /// </summary>
        public static string Player_Next {
            get {
                return ResourceManager.GetString("Player_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paus.
        /// </summary>
        public static string Player_Pause {
            get {
                return ResourceManager.GetString("Player_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spela.
        /// </summary>
        public static string Player_Play {
            get {
                return ResourceManager.GetString("Player_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spela nästa.
        /// </summary>
        public static string Player_PlayList_GoToNext {
            get {
                return ResourceManager.GetString("Player_PlayList_GoToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spela föregående.
        /// </summary>
        public static string Player_PlayList_GoToPrevious {
            get {
                return ResourceManager.GetString("Player_PlayList_GoToPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellista.
        /// </summary>
        public static string Player_Playlist_OpenPlaylist {
            get {
                return ResourceManager.GetString("Player_Playlist_OpenPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Föregående.
        /// </summary>
        public static string Player_Previous {
            get {
                return ResourceManager.GetString("Player_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flytta.
        /// </summary>
        public static string Playlist_ButtonMove {
            get {
                return ResourceManager.GetString("Playlist_ButtonMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort från spellista.
        /// </summary>
        public static string PlayList_ButtonRemoveFromPlaylist {
            get {
                return ResourceManager.GetString("PlayList_ButtonRemoveFromPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din spellista är tom..
        /// </summary>
        public static string Playlist_Empty {
            get {
                return ResourceManager.GetString("Playlist_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ta bort {0} avsnitt från spellista?.
        /// </summary>
        public static string Playlist_RemoveMultiplePlaylistItemsWarning {
            get {
                return ResourceManager.GetString("Playlist_RemoveMultiplePlaylistItemsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort avsnitt.
        /// </summary>
        public static string Playlist_RemoveMultiplePlaylistItemsWarning_Title {
            get {
                return ResourceManager.GetString("Playlist_RemoveMultiplePlaylistItemsWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellista.
        /// </summary>
        public static string Playlist_Title {
            get {
                return ResourceManager.GetString("Playlist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioStorm kan automatisk hämta avsnitt som inte blivit spelade. Avsnitten raderas automatisk ett tag efter att du har lyssnat på dom..
        /// </summary>
        public static string ProgramInfo_AutoDownload_Description {
            get {
                return ResourceManager.GetString("ProgramInfo_AutoDownload_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hur många avsnitt vill du ha i kö för det här programmet?.
        /// </summary>
        public static string ProgramInfo_AutoDownload_QueueSize_Description {
            get {
                return ResourceManager.GetString("ProgramInfo_AutoDownload_QueueSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga.
        /// </summary>
        public static string ProgramInfo_AutoDownload_QueueSize_None {
            get {
                return ResourceManager.GetString("ProgramInfo_AutoDownload_QueueSize_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett avsnitt.
        /// </summary>
        public static string ProgramInfo_AutoDownload_QueueSize_One {
            get {
                return ResourceManager.GetString("ProgramInfo_AutoDownload_QueueSize_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} avsnitt.
        /// </summary>
        public static string ProgramInfo_AutoDownload_QueueSize_X {
            get {
                return ResourceManager.GetString("ProgramInfo_AutoDownload_QueueSize_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämta avsnitt automatiskt.
        /// </summary>
        public static string ProgramInfo_AutoDownload_Title {
            get {
                return ResourceManager.GetString("ProgramInfo_AutoDownload_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortering.
        /// </summary>
        public static string ProgramInfo_Button_Sorting {
            get {
                return ResourceManager.GetString("ProgramInfo_Button_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämta avsnitt automatiskt.
        /// </summary>
        public static string ProgramInfo_Buttons_AutoDownload {
            get {
                return ResourceManager.GetString("ProgramInfo_Buttons_AutoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns inga avsnitt för det här programmet..
        /// </summary>
        public static string ProgramInfo_NoEpisodes {
            get {
                return ResourceManager.GetString("ProgramInfo_NoEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to När du ändrar sortering påverkar detta ordningen du ser avsnitten i listan samt vilken ordning de laddas ned om du har automatisk nedladdning aktiverat..
        /// </summary>
        public static string ProgramInfo_Sorting_Description {
            get {
                return ResourceManager.GetString("ProgramInfo_Sorting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I vilken ordning ska avsnitten sorteras?.
        /// </summary>
        public static string ProgramInfo_Sorting_Order_Description {
            get {
                return ResourceManager.GetString("ProgramInfo_Sorting_Order_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De nyaste avsnitten först.
        /// </summary>
        public static string ProgramInfo_Sorting_Order_NewestFirst {
            get {
                return ResourceManager.GetString("ProgramInfo_Sorting_Order_NewestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De äldsta avsnitten först.
        /// </summary>
        public static string ProgramInfo_Sorting_Order_OldestFirst {
            get {
                return ResourceManager.GetString("ProgramInfo_Sorting_Order_OldestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortering.
        /// </summary>
        public static string ProgramInfo_Sorting_Title {
            get {
                return ResourceManager.GetString("ProgramInfo_Sorting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du lägga till {0} program som favoriter?.
        /// </summary>
        public static string Programs_AddMultipleFavoritesWarning {
            get {
                return ResourceManager.GetString("Programs_AddMultipleFavoritesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägga till favoriter.
        /// </summary>
        public static string Programs_AddMultipleFavoritesWarning_Title {
            get {
                return ResourceManager.GetString("Programs_AddMultipleFavoritesWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Övrigt.
        /// </summary>
        public static string Programs_Category_Miscellaneous {
            get {
                return ResourceManager.GetString("Programs_Category_Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga program hittades..
        /// </summary>
        public static string Programs_NoProgramsFound {
            get {
                return ResourceManager.GetString("Programs_NoProgramsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök program.
        /// </summary>
        public static string Programs_SearchPrograms {
            get {
                return ResourceManager.GetString("Programs_SearchPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Programs_Title {
            get {
                return ResourceManager.GetString("Programs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort från tidigare.
        /// </summary>
        public static string Recent_ButtonRemoveItems {
            get {
                return ResourceManager.GetString("Recent_ButtonRemoveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to När du har spelat något program kan du se det här..
        /// </summary>
        public static string Recent_Empty {
            get {
                return ResourceManager.GetString("Recent_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förra veckan.
        /// </summary>
        public static string Recent_Group_LastWeek {
            get {
                return ResourceManager.GetString("Recent_Group_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Äldre.
        /// </summary>
        public static string Recent_Group_Older {
            get {
                return ResourceManager.GetString("Recent_Group_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna veckan.
        /// </summary>
        public static string Recent_Group_ThisWeek {
            get {
                return ResourceManager.GetString("Recent_Group_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort från tidigare.
        /// </summary>
        public static string Recent_RemoveFromRecent {
            get {
                return ResourceManager.GetString("Recent_RemoveFromRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ta bort {0} objekt från tidigare?.
        /// </summary>
        public static string Recent_RemoveMultipleRecentItemsWarning {
            get {
                return ResourceManager.GetString("Recent_RemoveMultipleRecentItemsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort tidigare.
        /// </summary>
        public static string Recent_RemoveMultipleRecentItemsWarning_Title {
            get {
                return ResourceManager.GetString("Recent_RemoveMultipleRecentItemsWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidigare.
        /// </summary>
        public static string Recent_Title {
            get {
                return ResourceManager.GetString("Recent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanske någon annan gång.
        /// </summary>
        public static string Review_MaybeLater {
            get {
                return ResourceManager.GetString("Review_MaybeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har du tid att lägga några sekunder på att sätta ett omdöme på RadioStorm? På så sätt gör du det enklare för andra att hitta vår lilla app - det skulle göra oss glada :)..
        /// </summary>
        public static string Review_Message {
            get {
                return ResourceManager.GetString("Review_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nej.
        /// </summary>
        public static string Review_No {
            get {
                return ResourceManager.GetString("Review_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gillar du RadioStorm?.
        /// </summary>
        public static string Review_Title {
            get {
                return ResourceManager.GetString("Review_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javisst!.
        /// </summary>
        public static string Review_Yes {
            get {
                return ResourceManager.GetString("Review_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortsätt spela.
        /// </summary>
        public static string SavedPlaylist_Play {
            get {
                return ResourceManager.GetString("SavedPlaylist_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparad spellista.
        /// </summary>
        public static string SavedPlaylist_Title {
            get {
                return ResourceManager.GetString("SavedPlaylist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töm cache.
        /// </summary>
        public static string Settings_Cache_ButtonClean {
            get {
                return ResourceManager.GetString("Settings_Cache_ButtonClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cachen är tömd..
        /// </summary>
        public static string Settings_Cache_Cleared {
            get {
                return ResourceManager.GetString("Settings_Cache_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tömmer cache....
        /// </summary>
        public static string Settings_Cache_Clearing {
            get {
                return ResourceManager.GetString("Settings_Cache_Clearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om du misstänker att du har problem med att informationen i programmet är för gammal, välj att rensa cachen för att hämta hem senaste informationen..
        /// </summary>
        public static string Settings_Cache_Description {
            get {
                return ResourceManager.GetString("Settings_Cache_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string Settings_Cache_Title {
            get {
                return ResourceManager.GetString("Settings_Cache_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivera inställningar för felsökning.
        /// </summary>
        public static string Settings_Debug_EnableDebugSettings {
            get {
                return ResourceManager.GetString("Settings_Debug_EnableDebugSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samlar ihop logfiler....
        /// </summary>
        public static string Settings_Debug_LogFiles_CollectingLogFiles {
            get {
                return ResourceManager.GetString("Settings_Debug_LogFiles_CollectingLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivera loggning (kräver omstart).
        /// </summary>
        public static string Settings_Debug_LogFiles_EnableLogToFile {
            get {
                return ResourceManager.GetString("Settings_Debug_LogFiles_EnableLogToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns inga loggfiler..
        /// </summary>
        public static string Settings_Debug_LogFiles_NoFiles {
            get {
                return ResourceManager.GetString("Settings_Debug_LogFiles_NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radera gamla loggfiler.
        /// </summary>
        public static string Settings_Debug_LogFiles_RemoveOldLogFiles {
            get {
                return ResourceManager.GetString("Settings_Debug_LogFiles_RemoveOldLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skicka loggfiler.
        /// </summary>
        public static string Settings_Debug_LogFiles_SendLogFiles {
            get {
                return ResourceManager.GetString("Settings_Debug_LogFiles_SendLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loggfiler.
        /// </summary>
        public static string Settings_Debug_LogFiles_Title {
            get {
                return ResourceManager.GetString("Settings_Debug_LogFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felsökning.
        /// </summary>
        public static string Settings_Debug_Title {
            get {
                return ResourceManager.GetString("Settings_Debug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta automatisk bort nedladdade avsnitt som är spelade efter:.
        /// </summary>
        public static string Settings_Downloads_AutoRemove_Description {
            get {
                return ResourceManager.GetString("Settings_Downloads_AutoRemove_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aldrig.
        /// </summary>
        public static string Settings_Downloads_AutoRemove_Option_Never {
            get {
                return ResourceManager.GetString("Settings_Downloads_AutoRemove_Option_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En dag.
        /// </summary>
        public static string Settings_Downloads_AutoRemove_Option_OneDay {
            get {
                return ResourceManager.GetString("Settings_Downloads_AutoRemove_Option_OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dagar.
        /// </summary>
        public static string Settings_Downloads_AutoRemove_Option_XDays {
            get {
                return ResourceManager.GetString("Settings_Downloads_AutoRemove_Option_XDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisk borttagning.
        /// </summary>
        public static string Settings_Downloads_AutoRemove_Title {
            get {
                return ResourceManager.GetString("Settings_Downloads_AutoRemove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to När hämtas nedladdningar?.
        /// </summary>
        public static string Settings_Downloads_Button_ShowDownladInformation {
            get {
                return ResourceManager.GetString("Settings_Downloads_Button_ShowDownladInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedladdningar hämtas automatiskt i bakgrunden när du inte använder enheten och du har tillgång till fritt Internet. Om du har fler än totalt {0} nedladdningar kommer inte fler nedladdningar att göras..
        /// </summary>
        public static string Settings_Downloads_DownladInformation {
            get {
                return ResourceManager.GetString("Settings_Downloads_DownladInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa meddelande när ett nytt avsnitt laddats ned automatiskt..
        /// </summary>
        public static string Settings_Downloads_General_ShowToastMessage {
            get {
                return ResourceManager.GetString("Settings_Downloads_General_ShowToastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allmänt.
        /// </summary>
        public static string Settings_Downloads_General_Title {
            get {
                return ResourceManager.GetString("Settings_Downloads_General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} spelade.
        /// </summary>
        public static string Settings_Downloads_Listened_Multiple {
            get {
                return ResourceManager.GetString("Settings_Downloads_Listened_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en spelad.
        /// </summary>
        public static string Settings_Downloads_Listened_Single {
            get {
                return ResourceManager.GetString("Settings_Downloads_Listened_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedladdningar.
        /// </summary>
        public static string Settings_Downloads_Title {
            get {
                return ResourceManager.GetString("Settings_Downloads_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal nedladdade avsnitt:.
        /// </summary>
        public static string Settings_Downloads_Usage_DownloadCount {
            get {
                return ResourceManager.GetString("Settings_Downloads_Usage_DownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort alla.
        /// </summary>
        public static string Settings_Downloads_Usage_RemoveAll {
            get {
                return ResourceManager.GetString("Settings_Downloads_Usage_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort spelade avsnitt.
        /// </summary>
        public static string Settings_Downloads_Usage_RemoveListened {
            get {
                return ResourceManager.GetString("Settings_Downloads_Usage_RemoveListened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utrymme:.
        /// </summary>
        public static string Settings_Downloads_Usage_SpaceUsage {
            get {
                return ResourceManager.GetString("Settings_Downloads_Usage_SpaceUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användning av lagringsutrymme.
        /// </summary>
        public static string Settings_Downloads_Usage_Title {
            get {
                return ResourceManager.GetString("Settings_Downloads_Usage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Använd levande panel..
        /// </summary>
        public static string Settings_LiveTile_Description {
            get {
                return ResourceManager.GetString("Settings_LiveTile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levande panel.
        /// </summary>
        public static string Settings_LiveTile_Title {
            get {
                return ResourceManager.GetString("Settings_LiveTile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avsnitt som laddats ned spelas alltid upp utan musik..
        /// </summary>
        public static string Settings_Play_DownloadNote {
            get {
                return ResourceManager.GetString("Settings_Play_DownloadNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to När ett avsnitt spelas upp, spela upp med musik om det är möjligt..
        /// </summary>
        public static string Settings_Play_PreferMusicDescription {
            get {
                return ResourceManager.GetString("Settings_Play_PreferMusicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppspelning.
        /// </summary>
        public static string Settings_Play_Title {
            get {
                return ResourceManager.GetString("Settings_Play_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om du loggar in med ditt Microsoft-konto så synkroniseras dina favoriter och vad du har lyssnat på mellan dina enheter. Detta sparas i mappen Appar på ditt OneDrive-konto..
        /// </summary>
        public static string Settings_Synchronize_Description {
            get {
                return ResourceManager.GetString("Settings_Synchronize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS! Den här versionen av RadioStorm synkroniserar data mot en testmiljö..
        /// </summary>
        public static string Settings_Synchronize_IsTestEnvironment {
            get {
                return ResourceManager.GetString("Settings_Synchronize_IsTestEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggad med {0}..
        /// </summary>
        public static string Settings_Synchronize_SignedInDetails {
            get {
                return ResourceManager.GetString("Settings_Synchronize_SignedInDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synkronisera nu.
        /// </summary>
        public static string Settings_Synchronize_SyncNow {
            get {
                return ResourceManager.GetString("Settings_Synchronize_SyncNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senaste synkroniseringen gjordes {0}..
        /// </summary>
        public static string Settings_Synchronize_SyncState_Done {
            get {
                return ResourceManager.GetString("Settings_Synchronize_SyncState_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen synkronisering har gjorts..
        /// </summary>
        public static string Settings_Synchronize_SyncState_None {
            get {
                return ResourceManager.GetString("Settings_Synchronize_SyncState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synkroniserar....
        /// </summary>
        public static string Settings_Synchronize_SyncState_Running {
            get {
                return ResourceManager.GetString("Settings_Synchronize_SyncState_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synkronisering.
        /// </summary>
        public static string Settings_Synchronize_Title {
            get {
                return ResourceManager.GetString("Settings_Synchronize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mörkt.
        /// </summary>
        public static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatiskt.
        /// </summary>
        public static string Settings_Theme_Default {
            get {
                return ResourceManager.GetString("Settings_Theme_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj vilket tema som ska användas. Du behöver starta om RadioStorm för att aktivera ändringarna..
        /// </summary>
        public static string Settings_Theme_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljust.
        /// </summary>
        public static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Settings_Theme_Title {
            get {
                return ResourceManager.GetString("Settings_Theme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inställningar.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanaler.
        /// </summary>
        public static string Start_JumpList_Channels {
            get {
                return ResourceManager.GetString("Start_JumpList_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in.
        /// </summary>
        public static string SynchonizingButton_State_SignIn {
            get {
                return ResourceManager.GetString("SynchonizingButton_State_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loggar in....
        /// </summary>
        public static string SynchonizingButton_State_SigningIn {
            get {
                return ResourceManager.GetString("SynchonizingButton_State_SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga ut.
        /// </summary>
        public static string SynchonizingButton_State_SignOut {
            get {
                return ResourceManager.GetString("SynchonizingButton_State_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fredag.
        /// </summary>
        public static string Weekday_Friday {
            get {
                return ResourceManager.GetString("Weekday_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Måndag.
        /// </summary>
        public static string Weekday_Monday {
            get {
                return ResourceManager.GetString("Weekday_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lördag.
        /// </summary>
        public static string Weekday_Saturday {
            get {
                return ResourceManager.GetString("Weekday_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söndag.
        /// </summary>
        public static string Weekday_Sunday {
            get {
                return ResourceManager.GetString("Weekday_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torsdag.
        /// </summary>
        public static string Weekday_Thursday {
            get {
                return ResourceManager.GetString("Weekday_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idag.
        /// </summary>
        public static string Weekday_Today {
            get {
                return ResourceManager.GetString("Weekday_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imorgon.
        /// </summary>
        public static string Weekday_Tomorrow {
            get {
                return ResourceManager.GetString("Weekday_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tisdag.
        /// </summary>
        public static string Weekday_Tuesday {
            get {
                return ResourceManager.GetString("Weekday_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onsdag.
        /// </summary>
        public static string Weekday_Wednesday {
            get {
                return ResourceManager.GetString("Weekday_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igår.
        /// </summary>
        public static string Weekday_Yesterday {
            get {
                return ResourceManager.GetString("Weekday_Yesterday", resourceCulture);
            }
        }
    }
}
