// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Pekspro.RadioStorm.GeneralDatabase.CompiledModel
{
    [DbContext(typeof(GeneralDatabaseContext))]
    public sealed partial class GeneralDatabaseContextModel : RuntimeModel
    {
        static GeneralDatabaseContextModel()
        {
            var model = new GeneralDatabaseContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static GeneralDatabaseContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
