// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Pekspro.RadioStorm.CacheDatabase.CompiledModel
{
    [DbContext(typeof(CacheDatabaseContext))]
    public partial class CacheDatabaseContextModel : RuntimeModel
    {
        static CacheDatabaseContextModel()
        {
            var model = new CacheDatabaseContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static CacheDatabaseContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
